// Turns the web wallet's Next.js App Router tree (src/app) into a route table
// for the extension's hash router. Every page.jsx becomes a lazily loaded
// route, wrapped in the layout.jsx files above it (the root layout.js is a
// server component and is replaced by src/app/Root.jsx).
//
// Folder conventions handled: [param], [...catchAll], [[...optionalCatchAll]],
// (group) folders (no URL segment) and _private folders (ignored).
const fs = require('fs');
const path = require('path');

const PAGE_FILES = ['page.jsx', 'page.js'];
const LAYOUT_FILES = ['layout.jsx'];

const findFile = (dir, names) =>
  names.map(name => path.join(dir, name)).find(file => fs.existsSync(file));

const toSegment = name => {
  let match = name.match(/^\[\[\.\.\.(\w+)\]\]$/);
  if (match) {
    return {type: 'optionalCatchAll', name: match[1]};
  }
  match = name.match(/^\[\.\.\.(\w+)\]$/);
  if (match) {
    return {type: 'catchAll', name: match[1]};
  }
  match = name.match(/^\[(\w+)\]$/);
  if (match) {
    return {type: 'dynamic', name: match[1]};
  }
  return {type: 'static', value: name};
};

const collect = (dir, segments, layouts, routes) => {
  const layout = segments.length ? findFile(dir, LAYOUT_FILES) : null;
  const nextLayouts = layout ? [...layouts, layout] : layouts;
  const page = findFile(dir, PAGE_FILES);
  if (page) {
    routes.push({segments, page, layouts: nextLayouts});
  }
  for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
    if (!entry.isDirectory() || entry.name.startsWith('_')) {
      continue;
    }
    if (entry.name === 'api' && !segments.length) {
      continue;
    }
    const isGroup = /^\(.*\)$/.test(entry.name);
    collect(
      path.join(dir, entry.name),
      isGroup ? segments : [...segments, toSegment(entry.name)],
      nextLayouts,
      routes,
    );
  }
};

// Static segments beat dynamic ones, which beat catch-alls (Next's order).
const RANK = {static: 0, dynamic: 1, catchAll: 2, optionalCatchAll: 3};
const compareRoutes = (a, b) => {
  const length = Math.max(a.segments.length, b.segments.length);
  for (let i = 0; i < length; i += 1) {
    const sa = a.segments[i];
    const sb = b.segments[i];
    if (!sa) return sb.type === 'optionalCatchAll' ? 1 : -1;
    if (!sb) return sa.type === 'optionalCatchAll' ? -1 : 1;
    if (RANK[sa.type] !== RANK[sb.type]) return RANK[sa.type] - RANK[sb.type];
  }
  return 0;
};

const generateRoutes = ({appDir, outFile}) => {
  const routes = [];
  collect(appDir, [], [], routes);
  routes.sort(compareRoutes);

  const imports = [];
  const importId = new Map();
  const lazyRef = file => {
    if (!importId.has(file)) {
      const id = `m${importId.size}`;
      importId.set(file, id);
      imports.push(
        `const ${id} = lazy(() => import(${JSON.stringify(file)}));`,
      );
    }
    return importId.get(file);
  };

  const notFound = findFile(appDir, ['not-found.jsx']);
  const errorPage = findFile(appDir, ['error.jsx']);
  const body = routes
    .map(route => {
      const page = lazyRef(route.page);
      const layouts = route.layouts.map(lazyRef);
      const id = path.relative(appDir, path.dirname(route.page)) || '/';
      return `  {id: ${JSON.stringify(id)}, segments: ${JSON.stringify(
        route.segments,
      )}, Page: ${page}, layouts: [${layouts.join(', ')}]},`;
    })
    .join('\n');

  const source = `// Generated by scripts/generate-routes.js from ${path.relative(
    path.dirname(outFile),
    appDir,
  )}. Do not edit.
import {lazy} from 'react';
${imports.join('\n')}

export const routes = [
${body}
];

export {default as NotFound} from ${JSON.stringify(notFound)};
export {default as ErrorPage} from ${JSON.stringify(errorPage)};
`;
  fs.mkdirSync(path.dirname(outFile), {recursive: true});
  if (!fs.existsSync(outFile) || fs.readFileSync(outFile, 'utf8') !== source) {
    fs.writeFileSync(outFile, source);
  }
  return routes.length;
};

module.exports = {generateRoutes};
